/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as BatchBatchIdRouteImport } from './routes/batch.$batchId'
import { Route as RecipeRecipeIdRouteImport } from './routes/recipe.$recipeId'
import { Route as KbRecipeRecipeIdRouteImport } from './routes/kb.recipe.$recipeId'
import { Route as RecipeRecipeIdEditRouteImport } from './routes/recipe.$recipeId_.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchBatchIdRoute = BatchBatchIdRouteImport.update({
  id: '/batch/$batchId',
  path: '/batch/$batchId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdRoute = RecipeRecipeIdRouteImport.update({
  id: '/recipe/$recipeId',
  path: '/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const KbRecipeRecipeIdRoute = KbRecipeRecipeIdRouteImport.update({
  id: '/kb/recipe/$recipeId',
  path: '/kb/recipe/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRecipeIdEditRoute = RecipeRecipeIdEditRouteImport.update({
  id: '/recipe/$recipeId_/edit',
  path: '/recipe/$recipeId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipes': typeof RecipesRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/kb/recipe/$recipeId': typeof KbRecipeRecipeIdRoute
  '/recipe/$recipeId/edit': typeof RecipeRecipeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipes': typeof RecipesRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/kb/recipe/$recipeId': typeof KbRecipeRecipeIdRoute
  '/recipe/$recipeId/edit': typeof RecipeRecipeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipes': typeof RecipesRoute
  '/batch/$batchId': typeof BatchBatchIdRoute
  '/recipe/$recipeId': typeof RecipeRecipeIdRoute
  '/kb/recipe/$recipeId': typeof KbRecipeRecipeIdRoute
  '/recipe/$recipeId_/edit': typeof RecipeRecipeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipes'
    | '/batch/$batchId'
    | '/recipe/$recipeId'
    | '/kb/recipe/$recipeId'
    | '/recipe/$recipeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipes'
    | '/batch/$batchId'
    | '/recipe/$recipeId'
    | '/kb/recipe/$recipeId'
    | '/recipe/$recipeId/edit'
  id:
    | '__root__'
    | '/'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipes'
    | '/batch/$batchId'
    | '/recipe/$recipeId'
    | '/kb/recipe/$recipeId'
    | '/recipe/$recipeId_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchesRoute: typeof BatchesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  KnowledgeRoute: typeof KnowledgeRoute
  RecipesRoute: typeof RecipesRoute
  BatchBatchIdRoute: typeof BatchBatchIdRoute
  RecipeRecipeIdRoute: typeof RecipeRecipeIdRoute
  KbRecipeRecipeIdRoute: typeof KbRecipeRecipeIdRoute
  RecipeRecipeIdEditRoute: typeof RecipeRecipeIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch/$batchId': {
      id: '/batch/$batchId'
      path: '/batch/$batchId'
      fullPath: '/batch/$batchId'
      preLoaderRoute: typeof BatchBatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId': {
      id: '/recipe/$recipeId'
      path: '/recipe/$recipeId'
      fullPath: '/recipe/$recipeId'
      preLoaderRoute: typeof RecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kb/recipe/$recipeId': {
      id: '/kb/recipe/$recipeId'
      path: '/kb/recipe/$recipeId'
      fullPath: '/kb/recipe/$recipeId'
      preLoaderRoute: typeof KbRecipeRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe/$recipeId_/edit': {
      id: '/recipe/$recipeId_/edit'
      path: '/recipe/$recipeId/edit'
      fullPath: '/recipe/$recipeId/edit'
      preLoaderRoute: typeof RecipeRecipeIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchesRoute: BatchesRoute,
  DisclaimerRoute: DisclaimerRoute,
  KnowledgeRoute: KnowledgeRoute,
  RecipesRoute: RecipesRoute,
  BatchBatchIdRoute: BatchBatchIdRoute,
  RecipeRecipeIdRoute: RecipeRecipeIdRoute,
  KbRecipeRecipeIdRoute: KbRecipeRecipeIdRoute,
  RecipeRecipeIdEditRoute: RecipeRecipeIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
