/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as RecipeRouteImport } from './routes/recipe'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as BatchesRouteImport } from './routes/batches'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as IndexRouteImport } from './routes/index'

const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeRoute = RecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesRoute = BatchesRouteImport.update({
  id: '/batches',
  path: '/batches',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipe': typeof RecipeRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipe': typeof RecipeRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/batches': typeof BatchesRoute
  '/disclaimer': typeof DisclaimerRoute
  '/knowledge': typeof KnowledgeRoute
  '/recipe': typeof RecipeRoute
  '/recipes': typeof RecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipe'
    | '/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipe'
    | '/recipes'
  id:
    | '__root__'
    | '/'
    | '/batch'
    | '/batches'
    | '/disclaimer'
    | '/knowledge'
    | '/recipe'
    | '/recipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  BatchesRoute: typeof BatchesRoute
  DisclaimerRoute: typeof DisclaimerRoute
  KnowledgeRoute: typeof KnowledgeRoute
  RecipeRoute: typeof RecipeRoute
  RecipesRoute: typeof RecipesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe': {
      id: '/recipe'
      path: '/recipe'
      fullPath: '/recipe'
      preLoaderRoute: typeof RecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches': {
      id: '/batches'
      path: '/batches'
      fullPath: '/batches'
      preLoaderRoute: typeof BatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  BatchesRoute: BatchesRoute,
  DisclaimerRoute: DisclaimerRoute,
  KnowledgeRoute: KnowledgeRoute,
  RecipeRoute: RecipeRoute,
  RecipesRoute: RecipesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
