import base from "../core/eslint.config.base.js";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

// Shared rules (style, imports, react-hooks, the @/-not-../ + no-lodash bans) live in
// the base config in packages/core. This file is only the app-specific overlay.
export default tseslint.config(
    ...base,
    {
        // generated by the router vite plugin; never hand-edited, so linting it
        // only produces findings nobody is allowed to fix
        ignores: ["src/routeTree.gen.ts"]
    },
    {
        files: ["**/*.{ts,tsx}"],
        plugins: { "react-refresh": reactRefresh },
        rules: {
            "react-refresh/only-export-components": ["warn", { allowConstantExport: true }]
        }
    },
    {
        // the hand-rolled lodash replacement: dot-path get/set over arbitrary object
        // shapes is inherently untyped, and `any` is the intended contract (callers cast).
        files: ["src/utils/func.ts"],
        rules: { "@typescript-eslint/no-explicit-any": "off" }
    }
);
