import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        ignores: [
            "dist",
            // generated by the router vite plugin; never hand-edited, so linting
            // it only produces findings nobody is allowed to fix
            "src/routeTree.gen.ts"
        ]
    },
    {
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        files: ["**/*.{ts,tsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: globals.browser
        },
        plugins: {
            "react-hooks": reactHooks,
            "react-refresh": reactRefresh
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
            // the codebase already uses a leading _ for deliberate throwaways —
            // destructured skips (`const [_, x] = ...`) and unused stub params.
            // Honor that convention rather than editing each site.
            "@typescript-eslint/no-unused-vars": ["error", {
                argsIgnorePattern: "^_",
                varsIgnorePattern: "^_",
                caughtErrorsIgnorePattern: "^_",
                destructuredArrayIgnorePattern: "^_"
            }]
        }
    },
    {
        // the hand-rolled lodash replacement: dot-path get/set over arbitrary
        // object shapes is inherently untyped, and `any` is the intended contract
        // (callers cast the result). CLAUDE.md points here as the deliberate
        // dynamic-access layer.
        files: ["src/utils/func.ts"],
        rules: { "@typescript-eslint/no-explicit-any": "off" }
    }
);
