import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import stylistic from "@stylistic/eslint-plugin";
import importX from "eslint-plugin-import-x";
import tseslint from "typescript-eslint";

export default tseslint.config(
    {
        ignores: [
            "dist",
            // generated by the router vite plugin; never hand-edited, so linting
            // it only produces findings nobody is allowed to fix
            "src/routeTree.gen.ts"
        ]
    },
    {
        extends: [js.configs.recommended, ...tseslint.configs.recommended],
        files: ["**/*.{ts,tsx}"],
        languageOptions: {
            ecmaVersion: 2020,
            globals: globals.browser
        },
        plugins: {
            "react-hooks": reactHooks,
            "react-refresh": reactRefresh,
            "@stylistic": stylistic,
            "import-x": importX
        },
        rules: {
            ...reactHooks.configs.recommended.rules,
            "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],

            // style conventions — codify what the code already does (double quotes,
            // semicolons), so these are near-zero auto-fixes rather than a reflow.
            "@stylistic/quotes": ["error", "double", { avoidEscape: true }],
            "@stylistic/semi": ["error", "always"],
            // the codebase is already uniformly 4-space; this just locks it in
            "@stylistic/indent": ["error", 4],

            // reach into a sibling workspace package by its name, not a relative
            // path that climbs out of packages/app (../../../../kb → @brewdocs.beer/kb)
            "import-x/no-relative-packages": "error",

            // group + alphabetize imports: external libs, then @brewdocs.beer/*
            // workspace packages, then @/ internal, then relative (parent→sibling)
            "import-x/order": ["error", {
                groups: ["builtin", "external", "internal", "parent", "sibling", "index"],
                pathGroups: [
                    { pattern: "@brewdocs.beer/**", group: "external", position: "after" },
                    { pattern: "@/**", group: "internal" }
                ],
                pathGroupsExcludedImportTypes: ["builtin"],
                "newlines-between": "never",
                alphabetize: { order: "asc", caseInsensitive: true }
            }],
            // the codebase already uses a leading _ for deliberate throwaways —
            // destructured skips (`const [_, x] = ...`) and unused stub params.
            // Honor that convention rather than editing each site.
            "@typescript-eslint/no-unused-vars": ["error", {
                argsIgnorePattern: "^_",
                varsIgnorePattern: "^_",
                caughtErrorsIgnorePattern: "^_",
                destructuredArrayIgnorePattern: "^_"
            }]
        }
    },
    {
        // Import conventions scoped to app source. Deliberately NOT applied to
        // build/script files at the package root (vite.config.ts, migrations/*),
        // which legitimately reach into sibling packages' internals by relative
        // path — the @/ alias and package-name rules are src concerns.
        files: ["src/**/*.{ts,tsx}"],
        rules: {
            // enforce the "no lodash" rule that until now lived only in CLAUDE.md —
            // the repo uses the hand-rolled utils/func.ts instead
            "no-restricted-imports": ["error", {
                paths: [{ name: "lodash", message: "Use the hand-rolled helpers in @/utils/func instead." }],
                patterns: [
                    { group: ["lodash", "lodash/*"], message: "Use the hand-rolled helpers in @/utils/func instead." },
                    // intra-app modules go through the @/ alias, not a relative path
                    // that climbs out of the current directory (../screen/x → @/screen/x).
                    // Same-dir ./ imports are fine.
                    { group: ["../*", "../**"], message: "Import intra-app modules via the @/ alias, not a relative parent path." }
                ]
            }]
        }
    },
    {
        // the hand-rolled lodash replacement: dot-path get/set over arbitrary
        // object shapes is inherently untyped, and `any` is the intended contract
        // (callers cast the result). CLAUDE.md points here as the deliberate
        // dynamic-access layer.
        files: ["src/utils/func.ts"],
        rules: { "@typescript-eslint/no-explicit-any": "off" }
    }
);
