name: Verify
run-name: "Verify"

on:
  pull_request:
    branches:
      - mainline

concurrency:
  group: verify-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  Verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}s
      - run: npm ci
      - run: npm test -ws
      - run: npm run build -ws
